project_id = "mbngbrdmzvpsnpcnesjv"

[functions.call-company-webhook]
verify_jwt = false

[functions.delete-user-webhook]
verify_jwt = false

[functions.reset-company-password]
verify_jwt = false

[functions.sync-company-status]
verify_jwt = false

[functions.sync-company-update]
verify_jwt = false

[functions.update-user-status]
verify_jwt = false