// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbngbrdmzvpsnpcnesjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibmdicmRtenZwc25wY25lc2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTk1NjAsImV4cCI6MjA2ODg3NTU2MH0.7cP9MP6eWPRDbUao6HSyjL6bCgneaqv6m8rryS0skOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});